### PR TITLE
fix #61

### LINKED ISSUE #61: Add support for USING clause for alterColumn
Postgres alter column often require explicit typecast with USING clause

Propose to add the ability for support 

```php
    $db->alterColumn('my_table', 'text_field', 'VARCHAR(255) USING text_field::varchar')
```

 https://github.com/yiisoft/db-pgsql/blob/master/src/QueryBuilder.php#L319

### PR DESCRIPTION
**Pull request by Insolita**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  |  #61

### CODE REVIEW

**Comment by terabytesoftw** [comment]
Tests fail because `testQueryLog` needs to be adjusted to the latest `yiisoft/log` changes.

**Review by terabytesoftw — APPROVED** [review]

**Comment by Insolita** [comment]
> Tests fail because `testQueryLog` needs to be adjusted to the latest `yiisoft/log` changes.

Is it required for any actions from me?

**Comment by terabytesoftw** [comment]
> > Tests fail because  needs to be adjusted to the latest  changes.`testQueryLog``yiisoft/log`
> 
> Is it required for any actions from me?

No, I only reported your pr this perfect 👍.

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
@terabytesoftw should we fix master first or merge it first? What do you prefer?

**Comment by terabytesoftw** [comment]
> @terabytesoftw should we fix master first or merge it first? What do you prefer?

I'm already fixing it when I finish I merge.

**Comment by terabytesoftw** [comment]
Thks 👍

**Pull request merged**
