### PR TITLE
Fix multiline default string

### PR DESCRIPTION
**Pull request by Tigrov**
* Fix multiline default value of string / text
* Fix single quote in default value

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

### CODE REVIEW

**Review by vjik — COMMENTED** [review]
Please, add line to changelog

**Review by vjik — APPROVED** [review]

**Review by terabytesoftw — APPROVED** [review]

**Comment by vjik** [comment]
@Tigrov Need test for negative numeric default values whose support has been added by last commit.

**Comment by samdark** [comment]
Created an issue for adding a test: https://github.com/yiisoft/db-pgsql/issues/298

**Comment by samdark** [comment]
👍

**Pull request merged**
