### PR TITLE
fix index column orders

### PR DESCRIPTION
**Pull request by Insolita**
| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  |❌
| Breaks BC?    | ❌
| Fixed issues  | #71

### CODE REVIEW

**Comment by terabytesoftw** [comment]
Awesome thank you very much.

**Comment by roxblnfk** [comment]
@Insolita can you add also an indents for this sql nowdoc block?

**Comment by Insolita** [comment]
> @Insolita can you add also an indents for this sql nowdoc block?

Sorry, it is not clear to me - what is wrong with indents

**Review by roxblnfk — APPROVED** [review]

**Review by samdark — APPROVED** [review]

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
