### PR TITLE
Update phpTypecast for bool type

### PR DESCRIPTION
**Pull request by Tigrov**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ❌
| Breaks BC?    | ❌
| Fixed issues  | -

### CODE REVIEW

**Review by samdark — APPROVED** [review]

**Review by terabytesoftw — APPROVED** [review]

**Review by vjik — APPROVED** [review]

**Comment by terabytesoftw** [comment]
Please add changelog line,

Thks,

**Comment by darkdef** [comment]
Please add line to changelog

**Comment by Tigrov** [comment]
@terabytesoftw

Hi. There are several minor changes. And a couple that will take time.
I will try to push the minor changes until the end of the week.

Thanks.

**Comment by terabytesoftw** [comment]
> @terabytesoftw
> 
> Hi. There are several minor changes. And a couple that will take time. I will try to push the minor changes until the end of the week.
> 
> Thanks.

thks

**Pull request merged**
